tokenizer_type: bytelevel_bpe
input_dir: data/dedup
tokenizer_dir: tokenizer

vocab_size: 16000

min_frequency: 2

special_tokens:
  - "<pad>"
  - "<bos>"
  - "<eos>"
  - "<unk>"

byte_fallback: true
lowercase: false


